name: Codecov + Jacoco
on: [ 'push', 'pull_request' ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Gradle build
        run: gradle build

      - name: Upload JaCoCo coverage to CodeCov
        uses: codecov/codecov-action@v3